DB_HOST = "127.0.0.1"
DB_USER = "root"
DB_PASS = "wyc990213"
DB_NAME = "db_slot"

IP_BLOCK_TIMES = 10
TIERS = ['first', 'second', 'third']

FIRST_TIER_POINTS = 10
SECOND_TIER_POINTS = 5
THIRD_TIER_POINTS = 1

FIRST_TIER_BONUS_POINTS = 3
SECOND_TIER_BONUS_POINTS = 2
THIRD_TIER_BONUS_POINTS = 1

RANDOM_USER = "Random user"

POINTS_ERROR_MESSAGE = "Your points aren't enough to join this round."